In [29]:
import random
import numpy as np
import pandas as pd
from scipy.stats import norm, truncnorm

df = pd.read_csv("given.csv")

In [26]:
#pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: /Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [57]:

def generate_ownership_distribution():
    num_owners = random.choices([1, 2, 3, 4], weights=[0.7, 0.2, 0.05, 0.05])[0]
    if num_owners == 1:
        return [100, 0, 0, 0, 0]
    else:
        remaining = 100
        ownerships = []
        for i in range(num_owners - 1):
            share = random.randint(20, remaining - (20 * (num_owners - (i + 1))))
            ownerships.append(share)
            remaining -= share
        ownerships.append(remaining)  
        ownerships.sort(reverse=True)  
        return ownerships + [0] * (5 - num_owners)  
        
def generate_business_structure():
    return random.choices(
        ["Sole Proprietorship", "LLC", "S Corporation (S-Corp)", "Partnership", "Franchise", "Nonprofit Organization", "Joint Venture"],
        weights=[0.35, 0.35, 0.25, 0.02, 0.01, 0.01, 0.01]  # Rare ones have low probability (<0.05)
    )[0]

# Function to generate a credit score following a normal FICO distribution
def generate_fico_score():
    fico_distribution = [(800, 850, 0.2), (740, 799, 0.36), (670, 739, 0.28),
                         (580, 669, 0.11), (300, 579, 0.05)]
    bucket = random.choices(fico_distribution, weights=[x[2] for x in fico_distribution])[0]
    return random.randint(bucket[0], bucket[1])

def generate_buisiness_score():
    buisiness_distribution = [(0, 99, 0.005), (100, 200, 0.99), (201, 300, 0.005)]
    bucket = random.choices(buisiness_distribution, weights=[x[2] for x in buisiness_distribution])[0]
    return random.randint(bucket[0], bucket[1])

def sample_dscr(mean=1.25, std=0.3, lower=0.25, upper=2.0):
    """ Sample DSCR from a truncated normal distribution """
    a, b = (lower - mean) / std, (upper - mean) / std
    return round(truncnorm.rvs(a, b, loc=mean, scale=std), 2)

def generate_financials():
    revenue = int(round(random.randint(150000, 1500000), -3))
    dscr = sample_dscr() 

    while True:
        business_debt = np.random.randint(50000, 500000)  
        noi = dscr * business_debt 
        
        if noi <= revenue:  
            break 
    
    return {
        "Revenue" : revenue,
        "DSCR": dscr,
        "NOI": int(noi),
        "Business Debt": business_debt
    }

# Function to generate DSCR values following a normal distribution
def generate_dscr():
    return round(max(0.25, min(2.0, norm.rvs(loc=1.25, scale=0.3))), 2)


# Generate corrected synthetic data
def generate_corrected_synthetic_data(n):
    data = []
    for i in range(n):
        applicant_id = i +1
        business_structure = generate_business_structure()
        #200 cities
        location = random.choice(["New York, NY", "Los Angeles, CA", "Chicago, IL", "Houston, TX", "Phoenix, AZ",
                                    "Philadelphia, PA", "San Antonio, TX", "San Diego, CA", "Dallas, TX", "San Jose, CA",
                                    "Austin, TX", "Jacksonville, FL", "Fort Worth, TX", "Columbus, OH", "Charlotte, NC",
                                    "San Francisco, CA", "Indianapolis, IN", "Seattle, WA", "Denver, CO", "Washington, DC",
                                    "Boston, MA", "El Paso, TX", "Nashville, TN", "Detroit, MI", "Oklahoma City, OK",
                                    "Portland, OR", "Las Vegas, NV", "Memphis, TN", "Louisville, KY", "Baltimore, MD",
                                    "Milwaukee, WI", "Albuquerque, NM", "Tucson, AZ", "Fresno, CA", "Mesa, AZ",
                                    "Sacramento, CA", "Atlanta, GA", "Kansas City, MO", "Colorado Springs, CO", "Miami, FL",
                                    "Raleigh, NC", "Omaha, NE", "Long Beach, CA", "Virginia Beach, VA", "Oakland, CA",
                                    "Minneapolis, MN", "Tulsa, OK", "Tampa, FL", "Arlington, TX", "New Orleans, LA",
                                    "Wichita, KS", "Cleveland, OH", "Bakersfield, CA", "Aurora, CO", "Anaheim, CA",
                                    "Honolulu, HI", "Santa Ana, CA", "Riverside, CA", "Corpus Christi, TX", "Lexington, KY",
                                    "Stockton, CA", "Henderson, NV", "Saint Paul, MN", "St. Louis, MO", "Cincinnati, OH",
                                    "Pittsburgh, PA", "Greensboro, NC", "Anchorage, AK", "Plano, TX", "Lincoln, NE",
                                    "Orlando, FL", "Irvine, CA", "Newark, NJ", "Durham, NC", "Chula Vista, CA",
                                    "Toledo, OH", "Fort Wayne, IN", "St. Petersburg, FL", "Laredo, TX", "Jersey City, NJ",
                                    "Chandler, AZ", "Madison, WI", "Lubbock, TX", "Scottsdale, AZ", "Reno, NV",
                                    "Buffalo, NY", "Gilbert, AZ", "Glendale, AZ", "North Las Vegas, NV", "Winston-Salem, NC",
                                    "Chesapeake, VA", "Norfolk, VA", "Fremont, CA", "Garland, TX", "Irving, TX",
                                    "Hialeah, FL", "Richmond, VA", "Boise, ID", "Spokane, WA", "Baton Rouge, LA",
                                    "Tacoma, WA", "San Bernardino, CA", "Modesto, CA", "Fontana, CA", "Des Moines, IA",
                                    "Moreno Valley, CA", "Santa Clarita, CA", "Fayetteville, NC", "Birmingham, AL", "Oxnard, CA",
                                    "Rochester, NY", "Port St. Lucie, FL", "Grand Rapids, MI", "Huntsville, AL", "Salt Lake City, UT",
                                    "Frisco, TX", "Yonkers, NY", "Amarillo, TX", "Glendale, CA", "Huntington Beach, CA",
                                    "McKinney, TX", "Montgomery, AL", "Augusta, GA", "Aurora, IL", "Akron, OH",
                                    "Little Rock, AR", "Tempe, AZ", "Columbus, GA", "Overland Park, KS", "Grand Prairie, TX",
                                    "Tallahassee, FL", "Cape Coral, FL", "Mobile, AL", "Knoxville, TN", "Shreveport, LA",
                                    "Worcester, MA", "Ontario, CA", "Vancouver, WA", "Sioux Falls, SD", "Chattanooga, TN",
                                    "Brownsville, TX", "Fort Lauderdale, FL", "Providence, RI", "Newport News, VA", "Rancho Cucamonga, CA",
                                    "Santa Rosa, CA", "Peoria, AZ", "Oceanside, CA", "Elk Grove, CA", "Salem, OR",
                                    "Pembroke Pines, FL", "Eugene, OR", "Garden Grove, CA", "Cary, NC", "Fort Collins, CO",
                                    "Corona, CA", "Springfield, MO", "Jackson, MS", "Alexandria, VA", "Hayward, CA",
                                    "Clarksville, TN", "Lakewood, CO", "Lancaster, CA", "Salinas, CA", "Palmdale, CA",
                                    "Hollywood, FL", "Springfield, MA", "Macon, GA", "Kansas City, KS", "Sunnyvale, CA",
                                    "Pomona, CA", "Killeen, TX", "Escondido, CA", "Pasadena, TX", "Naperville, IL",
                                    "Bellevue, WA", "Joliet, IL", "Murfreesboro, TN", "Midland, TX", "Rockford, IL",
                                    "Paterson, NJ", "Savannah, GA", "Bridgeport, CT", "Torrance, CA", "McAllen, TX",
                                    "Syracuse, NY", "Surprise, AZ", "Denton, TX", "Roseville, CA", "Thornton, CO",
                                    "Miramar, FL", "Pasadena, CA", "Mesquite, TX", "Olathe, KS", "Dayton, OH",
                                    "Carrollton, TX", "Waco, TX", "Orange, CA", "Fullerton, CA", "Charleston, SC",
                                    "West Valley City, UT", "Visalia, CA", "Hampton, VA", "Gainesville, FL", "Warren, MI",
                                    "Coral Springs, FL", "Cedar Rapids, IA", "Round Rock, TX", "Sterling Heights, MI", "Kent, WA"])
                                    
        # 155 NAICS small business codes (includes "522110, 522120, 522130, 522298, 713210, 813110, 531110, 531120, 813940" which are bank does not lend a loan)
        naics = random.choice([311812, 312120, 323111, 325620, 332710, 333112, 337110, 339950, 423910, 424410,
                                441110, 441310, 442110, 443142, 444130, 445110, 445210, 445292, 446110, 448120,
                                448310, 451110, 451211, 453310, 453920, 481211, 484110, 484121, 488510, 491110,
                                511110, 512110, 515120, 517311, 518210, 519130, 522110, 522120, 522130, 522298,
                                523930, 524210, 531110, 531120, 531210, 532111, 532292, 541110, 541211, 541330,
                                541430, 541511, 541611, 541810, 541922, 561311, 561720, 561730, 561740, 561990,
                                611110, 611420, 611610, 621111, 621210, 621310, 621320, 621330, 621391, 621420,
                                621491, 621610, 621910, 623220, 624120, 624190, 624410, 711110, 711130, 711320,
                                711410, 711510, 712190, 713210, 713940, 721110, 722310, 722320, 722511, 722513,
                                722515, 811111, 811121, 811192, 811310, 812112, 812113, 812199, 812310, 812910,
                                813110, 813410, 813920, 813940, 921120, 921130, 921190, 922120, 922140, 922160,
                                923110, 924120, 925110, 926120, 927110, 928110, 928120, 928130, 929110, 929120,
                                931110, 931120, 931130, 931140, 931150, 931160, 931170, 931180, 931190, 931200,
                                931210, 931220, 931230, 931240, 931250, 931260, 931270, 931280, 931290, 931300,
                                931310, 931320, 931330, 931340, 931350, 931360, 931370, 931380, 931390, 931400,
                                931410, 931420, 931430, 931440, 931450, 931460, 931470, 931480, 931490, 931500,
                                931510, 931520, 931530, 931540, 931550])

        # Business ownership distribution
        ownership_distribution = generate_ownership_distribution()

        personal_credit_score = generate_fico_score()
        business_credit_score = generate_buisiness_score()

        net_profit_margin = round(random.uniform(0, 15), 2)

        # Generate financials (DSCR, NOI, Business Debt)
        financials_2_years_ago = generate_financials()
        financials_1_year_ago = generate_financials()
        financials_latest_year = generate_financials()

        industry_experience = random.randint(0, 20)
        managerial_experience = random.randint(0, 20)
        years_in_business = random.randint(0, 15)

        collateral_availability = random.choice([True, False])
        loan_amount = int(round(random.randint(450000, 5050000), -3))

        fast_approval = loan_amount < 500000

        for_profit = business_structure != "Nonprofit Organization"
        acquisition_request = random.choice([True, False])

        # Encode loan purposes as boolean columns
        loan_purposes = [
            "Working Capital", "Business Expansion", "Equipment Purchase or Leasing", "Inventory Purchase",
            "Real Estate Acquisition or Improvement", "Business Acquisition or Buyout", "Refinancing Existing Debt",
            "Emergency Funds", "Franchise Financing", "Contract Financing", "Licensing or Permits", "Line of Credit Establishment"
        ]
        loan_purpose_flags = {purpose: random.choice([True, False]) for purpose in loan_purposes}

        row = [
            applicant_id, business_structure, "US", location, naics, *ownership_distribution,
            personal_credit_score, business_credit_score, financials_2_years_ago["Revenue"], financials_1_year_ago["Revenue"],
            financials_latest_year["Revenue"], net_profit_margin,
            financials_2_years_ago["Business Debt"], financials_1_year_ago["Business Debt"], financials_latest_year["Business Debt"],
            financials_2_years_ago["NOI"], financials_1_year_ago["NOI"], financials_latest_year["NOI"],
            financials_2_years_ago["DSCR"], financials_1_year_ago["DSCR"], financials_latest_year["DSCR"],
            industry_experience, managerial_experience, years_in_business,
            collateral_availability, loan_amount, fast_approval, for_profit, acquisition_request, *loan_purpose_flags.values()
        ]

        data.append(row)

    # Create DataFrame with column names
    columns = [
        "Applicant ID", "Business Structure", "Country", "Location", "NAICS",
        "Business Ownership (1)", "Business Ownership (2)", "Business Ownership (3)", "Business Ownership (4)", "Business Ownership (5)",
        "Personal Credit Score", "Business Credit Score",
        "Annual Revenue (2 years ago)", "Annual Revenue (1 year ago)", "Annual Revenue (latest year)", "Net Profit Margin",
        "Business Debt (2 years ago)", "Business Debt (1 year ago)", "Business Debt (latest year)",
        "NOI (2 years ago)", "NOI (1 year ago)", "NOI (latest year)",
        "DSCR (2 years ago)", "DSCR (1 year ago)", "DSCR (latest year)",
        "Industry Experience", "Managerial Experience", "Years in Business",
        "Collateral Availability", "Loan Amount", "Fast Approval", "For Profit", "Acquisition Request",
        "Working Capital", "Business Expansion", "Equipment Purchase or Leasing", "Inventory Purchase",
        "Real Estate Acquisition or Improvement", "Business Acquisition or Buyout", "Refinancing Existing Debt",
        "Emergency Funds", "Franchise Financing", "Contract Financing", "Licensing or Permits", "Line of Credit Establishment"
    ]

    corrected_df = pd.DataFrame(data, columns=columns)
    return corrected_df

# Generate the corrected dataset
corrected_synthetic_df = generate_corrected_synthetic_data(500)

In [58]:
corrected_synthetic_df.to_csv("Dummy.csv")
corrected_synthetic_df.to_excel("Dummy.xlsx", sheet_name="Modified Data", index=False)

In [32]:
corrected_synthetic_df

,Applicant ID,Business Structure,Country,Location,NAICS,Business Ownership (1),Business Ownership (2),Business Ownership (3),Business Ownership (4),Business Ownership (5),...,Equipment Purchase or Leasing,Inventory Purchase,Real Estate Acquisition or Improvement,Business Acquisition or Buyout,Refinancing Existing Debt,Emergency Funds,Franchise Financing,Contract Financing,Licensing or Permits,Line of Credit Establishment
0,1,S Corporation (S-Corp),US,"Columbus, GA",929110,100,0,0,0,0,...,False,False,True,False,False,True,False,False,False,False
1,2,LLC,US,"Richmond, VA",928110,64,36,0,0,0,...,True,True,True,False,False,False,True,True,False,False
2,3,LLC,US,"Moreno Valley, CA",923110,100,0,0,0,0,...,False,False,True,False,False,True,False,False,False,True
3,4,LLC,US,"Corpus Christi, TX",921130,100,0,0,0,0,...,False,False,False,False,True,False,False,False,True,False
4,5,Sole Proprietorship,US,"San Francisco, CA",931480,100,0,0,0,0,...,False,True,True,False,True,False,False,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,196,S Corporation (S-Corp),US,"Corona, CA",531110,100,0,0,0,0,...,False,True,False,True,False,False,False,True,False,False
196,197,LLC,US,"Knoxville, TN",931270,100,0,0,0,0,...,False,True,True,True,True,True,True,True,False,False
197,198,Sole Proprietorship,US,"Oklahoma City, OK",621420,100,0,0,0,0,...,False,True,True,True,True,True,False,False,False,True
198,199,LLC,US,"Jacksonville, FL",722310,100,0,0,0,0,...,False,True,True,True,True,True,False,True,False,True
199,200,S Corporation (S-Corp),US,"Round Rock, TX",621111,40,34,26,0,0,...,False,True,True,True,True,False,True,True,False,True